### ISSUE TITLE
It doesn't work along with sanity-shopify-studio 

### ISSUE THREAD

**Issue by bdoroshev** [sanity-io/hydrogen-sanity-demo#21] opened 2023-01-22 16:41 UTC
It doesn't work along with github.com/sanity-io/sanity-shopify-studio. I use npx @sanity/cli init --template shopify --project secret --dataset production. After that I run through yarn dev, I get the error "Internal server error: Cannot read properties of undefined (reading 'config') Plugin: vite:css" in studio, although all I did was change the projectId in sanity.config in this starter.

**Comment by Nichtkunst** [comment] 2023-03-25 08:58
I have exactly the Same issue.

**Comment by thebiggianthead** [comment] 2023-04-21 13:39
Closing this here as this is a duplicate of the issue on the Studio repo: https://github.com/sanity-io/sanity-shopify-studio/issues/14 - which is the right repo for the issue to live on. Thanks!

**Closed by thebiggianthead** 2023-04-21 13:39 UTC
